name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x] # Specify desired Node versions

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: |
          frontend/package-lock.json
          backend/package-lock.json

    - name: Install Frontend Dependencies
      working-directory: ./frontend
      run: npm ci

    - name: Install Backend Dependencies
      working-directory: ./backend
      run: npm ci

    # Placeholder for linting - Requires ESLint/Prettier setup
    # - name: Run Linter
    #   run: |
    #     cd frontend && npm run lint
    #     cd ../backend && npm run lint # Assuming lint scripts exist

    # Placeholder for tests - Requires test setup
    # - name: Run Tests
    #   run: |
    #     cd frontend && npm test
    #     cd ../backend && npm test # Assuming test scripts exist

    - name: Build Frontend
      working-directory: ./frontend
      run: npm run build 